"""add url, data columns

Revision ID: 39bb2d0bee49
Revises: 1ae2379344ca
Create Date: 2015-11-08 16:08:00.285226

"""

# revision identifiers, used by Alembic.
revision = '39bb2d0bee49'
down_revision = '1ae2379344ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'items', sa.Column('rule', sa.String(), nullable=True))
    op.add_column(u'items', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'items', 'type')
    op.drop_column(u'items', 'rule')
    op.drop_table('datas')
    op.drop_table('urls')
    ### end Alembic commands ###
