"""empty message

Revision ID: 4f18134d1596
Revises: None
Create Date: 2016-01-12 13:43:00.541475

"""

# revision identifiers, used by Alembic.
revision = '4f18134d1596'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('headers', sa.String(), nullable=True),
    sa.Column('proxy', sa.String(), nullable=True),
    sa.Column('thread_num', sa.Integer(), nullable=True),
    sa.Column('delay_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rule1', sa.String(), nullable=True),
    sa.Column('rule2', sa.String(), nullable=True),
    sa.Column('exclude', sa.String(), nullable=True),
    sa.Column('include', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('rule1', sa.String(), nullable=True),
    sa.Column('rule2', sa.String(), nullable=True),
    sa.Column('exclude', sa.String(), nullable=True),
    sa.Column('include', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('urls')
    op.drop_table('tags')
    op.drop_table('tasks')
    ### end Alembic commands ###
